### ISSUE TITLE
TSV & ESV swapped on info screen (top screen).

### ISSUE THREAD

**Issue by winneon** [BernardoGiordano/PKSV#1]
I'm assuming PSV means TSV throughout this report, as I have never heard of the PSV term before.

Shown in all screenshots and in the application itself, the PSV & ESV slots per Pokemon seem to be swapped. The TSV is shown on the bottom of the bottom screen, but for all Pokemon **except shinies** it's displayed as the ESV on the "PSV / TSV" slot.

**Comment by BernardoGiordano** [comment]
fixed
